# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: 'Publish package to npm'

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'

      - name: 'Cache Node dependencies'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install dependencies'
        run: 'npm install'

      - name: 'Run tests'
        run: 'npm test'

      - name: 'Publish to npm registry'
        run: 'npm publish --access public'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
